name: build_test_and_docs

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, edited, synchronize]

jobs:
  native_tasks:
    name: Native environment checks
    runs-on: ubuntu-latest
    container: italocjs/track_env:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /root/.platformio/.cache
          key: ${{ runner.os }}-pio   

      - name: Native build
        run: cd app/ && pio run -e native

      - name: Native test
        run: cd app/ && pio test -e native

  esp32dev_tasks:
    name: ESP32DEV environment checks
    needs: native_tasks
    runs-on: ubuntu-latest
    container: italocjs/track_env:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /root/.platformio/.cache
          key: ${{ runner.os }}-pio   

      - name: esp32dev remote test
        env: 
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
          ESP32: true
        run: cd app/ && pio remote --agent raspberrypi test -e esp32dev --upload-port /dev/ttyUSB0

      - name: esp32dev build and flash remote
        env: 
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
          ESP32: true
        run: cd app/ && pio remote --agent raspberrypi run -e esp32dev -t upload --upload-port /dev/ttyUSB0

  doxygen:
    name: Generate Doxygen Documentation
    needs: esp32dev_tasks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "Doxyfile"
        working-directory: "app/"
    
    - name: Deploy
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/doxygen_out/html/