name: Native and embedded remote testing

on:
  # push:
  #   branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [ opened, edited, synchronize]
    # types: [ opened, edited]

jobs:
  native_tasks:
    name: Native environment checks
    runs-on: ubuntu-latest
    container: italocjs/track_env:latest
    #italocjs/track_env:latest is used to provide a pre-loaded environment with the platformio packages preinstalled
    #if you change the board or the package requirements in platformio.ini you should build, upload and replace the image used here.
    # Use this to build the image based on the current Dockerfile on root folder
    # docker build -t italocjs/track_env:latest .
    # Push the image (but to your own repo, you can change the name)
    # docker push italocjs/track_env:latest
    #env updated
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /root/.platformio/.cache
          key: ${{ runner.os }}-pio   

      - name: Native build
        run: pio run -e native

      - name: Native test
        run: pio test -e native

  esp32dev_tasks:
    name: ESP32DEV environment checks
    runs-on: ubuntu-latest
    container: italocjs/track_env:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /root/.platformio/.cache
          key: ${{ runner.os }}-pio   

      - name: esp32dev remote test
        env: 
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
          ESP32: true
        run: pio remote --agent raspberrypi test -e esp32dev --upload-port /dev/ttyUSB0

      - name: esp32dev build and flash remote
        env: 
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
          ESP32: true
        run: pio remote --agent raspberrypi run -e esp32dev -t upload --upload-port /dev/ttyUSB0